language: node_js
node_js:
  - node
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
services:
  - xvfb
deploy:
  - provider: npm
    edge: true
    email: "fabien.levavasseur@gmail.com"
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - '_r.js'
      - '_r.js.map'
      - '_r.min.js'
      - '_r.min.js.map'
      - '_r.d.ts'
      - '_r.es6.js'
      - '_r.es6.js.map'
      - '../dist/babylon-runtime-${TRAVIS_TAG}.zip'
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bash ../tools/discord-bot/new-release.sh success $WEBHOOK_URL
    on:
      tags: true
